apiVersion: v1
kind: Service
metadata:
  name: hello-world-load-balancer
  namespace: default

spec:
  selector:
    app: hello-world
  ports:
    - port: 5050
      targetPort: 5050
  type: LoadBalancer